### ISSUE TITLE
Missing Notarization  - Fails to run on recent MacOS

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#123]
**Describe the bug**
Reported via [Hacker News](https://news.ycombinator.com/item?id=22174735), and similar to [Microsoft/ApplicationInspector#341](https://github.com/microsoft/AttackSurfaceAnalyzer/issues/341), we're going to need to get binaries distributed for MacOS notarized if they're going to run there.

**To Reproduce**
TBD, we'll test this out later this week. It's possible that "dotnet ApplicationInspector.dll" might work, assuming the .NET Core runner is notatized.

**Expected behavior**
The application should run normally.

**Screenshots**
n/a

**Desktop (please complete the following information):**
- Recent MacOS versions.

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by guyacosta** [comment]
Investigation: This appears related to .NET core including version 3.1 "macOS Catalina introduced new security features which affect the .NET Core installers. If you run the installer after downloading using a web browser, a warning dialog will open stating the package "...can't be opened because Apple cannot check it for malicious software.", and the installation will be stopped.

To override this behavior, go to Settings : Security & Privacy and choose "Open Anyway" next to the dotnet installer text.

We are working to update our installers for the new Catalina requirements. These will be released during an upcoming monthly update." -see https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015

**Comment by guyacosta** [comment]
Investigation: issue extends beyond .net apps.  https://www.cultofmac.com/672576/cant-launch-your-apps-on-macos-catalina-heres-the-fix/

**Comment by guyacosta** [comment]
Again, this appears to be a general .Net Core issue that Microsoft is working on as mentioned earlier and not specific to this application.  See the .Net core release document link above for more including details of how to resolve for now.
