### ISSUE TITLE
tagdiff fails with -o on ubuntu (appinspector 1.0.27)

### ISSUE THREAD

**Issue by d-karlss** [microsoft/ApplicationInspector#155]
**Describe the bug**
When running 'tagdiff' with the -o flag, the application fails to access the output directory for some reason.

**To Reproduce**
AppInspector.dll tagdiff -x high --src1 proj1 --src2 proj2 -o ~/tmp

**Expected behavior**
No runtime error

**Screenshots**

![image](https://user-images.githubusercontent.com/53612676/75984135-2091b680-5eea-11ea-926b-79c218ead201.png)

**Desktop (please complete the following information):**
Ubuntu 18.04.4 LTS

**Comment by guyacosta** [comment]
Looking into thanks.

**Comment by guyacosta** [comment]
Listen I am not seeing the issue having tested both the ~tmp file name is used or a directory /tmp is created and a filename is included which your example omitted so that it is referencing only a directory.  I'd look at that.  See my results here.
![tagdiffinvestigate1](https://user-images.githubusercontent.com/47648296/76045294-7af23d80-5f11-11ea-9d90-6da37f55a08e.png)

**Comment by d-karlss** [comment]
Oh, so it happens when you pass an existing directory instead of the path to a non-existing file.
So -o /tmp will not work if tmp is an already existing directly, maybe some error handling is missing.

**Comment by guyacosta** [comment]
I think the problem was just that your arg didn't include a filename at the end of the directory.  Note the directory must already exists as the app won't create the directory and file referenced.  So, if tmp is a directory and you only include -o /tmp that won't work but -o /temp/out.txt will work.  Cheers.
