### ISSUE TITLE
Analyze Error No Compressed File

### ISSUE THREAD

**Issue by imrzegarra** [microsoft/ApplicationInspector#161]
**Describe the bug**
D:\ApplicationInspector_1.1.5>ApplicationInspector.CLI.exe analyze -s D:\emailba\
Microsoft Application Inspector 1.1.5+ed45aa547b
Analyze command running
Decompressing files...
Problem while decompressing D:\emailba\WebContent\WEB-INF\lib\aws-java-sdk-core-1.11.543.jar: Unzip and try running on uncompressed files.
A runtime error has occured.  Please see log file for more information.

**To Reproduce**
D:\ApplicationInspector_1.1.5>ApplicationInspector.CLI.exe analyze -s D:\emailba\

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by guyacosta** [comment]
Can you rerun using the detailed log argument which may offer an additional clue.  Note that most of the 3rd party components that handle decompression will balk at some types of compression formats that may not implement more modern standards.  Use the -v debug argument and attach the log if you still think it is not something wrong with the file.

**Comment by imrzegarra** [comment]
Log file
[log.txt](https://github.com/microsoft/ApplicationInspector/files/4312473/log.txt)


It works in old versions

**Comment by guyacosta** [comment]
Investigating.  Yeah, confirmed that it's not the .jar format itself which works but be advised it is likely something that will need to be sent as an issue in the compression library which appears to be one of the best available.  I'll dig a bit further.

**Comment by scovetta** [comment]
I was able to reproduce this as well. I believe the problem is in the ApplicationInspector.CLI.deps.json file that's created. I don't know *why*, but around line 900, there was an entry:

```
      "SharpZipLib/1.2.0": {
         "runtime": { }
        }
      },
```

In similar projects, the section specified the DLL, like:
```
      "SharpZipLib/1.2.0": {
         "runtime": {
          "lib/netstandard2.0/ICSharpCode.SharpZipLib.dll": {
            "assemblyVersion": "1.2.0.246",
            "fileVersion": "1.2.0.246"
          }
        }
      },
```

Since the DLL file is present in the release, I just copy/pasted that section into the .deps file, and things appear to work.

Now we just need to figure out why the build isn't including the reference normally.

**Comment by guyacosta** [comment]
Thanks for the investigation.  Will continue this.

**Comment by guyacosta** [comment]
Updates.  Looks like the break was introduced after our nuget restructure a week back because older versions are not missing the runtime target info.  I confirm the missing info breaks ability to unzip any package! Haven't identified any help online for this.  The file is odd in that all projects list their dependent packages except the MultiExtractor which only has "MultiExtractor/1.1.0.0": {
        "runtime": {
          "MultiExtractor.dll": {
            "assemblyVersion": "1.1.0.0",
            "fileVersion": "1.1.13.19883"
          }
        }
      }
I would have thought the SharpZipLib would be listed under it not the ...CLI project.  There are other packages that don't specify a runtime target for reasons that are unclear as well e.g.  "MediaTypeMap.Core/2.3.3": {},
"Microsoft.NETCore.Platforms/2.1.2": {},
"Nerdbank.GitVersioning/3.0.50": {},

Going to enlist @daalcant as well to assist in the investigation.

**Comment by gfs** [comment]
Can you try removing and readding the packages to the correct locations using Visual Studio? That should hopefully repopulate the information again.

**Comment by guyacosta** [comment]
Did that -no help.  Release v1.0.27 didn't have the issue but the next one did where made the first restructure for NuGet breaking out the CLI vs Command projects and updating the pipeline.

**Comment by gfs** [comment]
It builds fine for me on Mac OS.

From `ApplicationInspector.CLI.deps.json`
```   
"SharpZipLib/1.2.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-zvWa/L02JHNatdtjya6Swpudb2YEHaOLHL1eRrqpjm71iGRNUNONO5adUF/9CHbSJbzhELW1UoH4NGy7n7+3bQ==",
      "path": "sharpziplib/1.2.0",
      "hashPath": "sharpziplib.1.2.0.nupkg.sha512"
    },
```

**Comment by guyacosta** [comment]
Hmm, it's not so much build related but runtime behavior.  Note the runtime info is still missing in that snippet -see the previous comments.  There are usually 2 sections.

**Comment by daalcant** [comment]
Somewhere along the line, SharpZipLib was removed as a dependency. If you re-add it, "ICSharpCode.SharpZipLib.dll" gets added back into the build output, and the deps.json file reflects this as it generates the previously mentioned runtime info.

**Comment by guyacosta** [comment]
It is already a dependency for the Commands project.  Removing and readding does not fix the issue with the deps.json.  Do you mean it should be added independently as a dependency for one of the other projects?

**Comment by guyacosta** [comment]
Confirmed missing when project restructure was created.  Not sure how the partial entry was still there nor what I was looking i.e. ghosts in the machine.  Verifying PR now.
