### ISSUE TITLE
NuGet library failing with "Invalid -v argument value"

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#177]
**Describe the bug**
The `AnalyzeCommand` throws an OpException when used.

**To Reproduce**
```
        static void Main(string[] args)
        {
            AnalyzeCommandOptions options = new AnalyzeCommandOptions();
            AnalyzeCommand command = new AnalyzeCommand(options);
            options.SourcePath = ".";

            string result = command.GetResult(); //process results as desired
            Console.WriteLine(result);
        }
```

Exception trace:
```	ApplicationInspector.Commands.dll!Microsoft.ApplicationInspector.Commands.Utils.SetupLogging(Microsoft.ApplicationInspector.Commands.AllCommandOptions opts)	Unknown
 	ApplicationInspector.Commands.dll!Microsoft.ApplicationInspector.Commands.Utils.SetupLogging()	Unknown
 	ApplicationInspector.Commands.dll!Microsoft.ApplicationInspector.Commands.WriteOnce.SafeLog(string message, NLog.LogLevel logLevel)	Unknown
 	ApplicationInspector.Commands.dll!Microsoft.ApplicationInspector.Commands.AnalyzeCommand.ConfigOutput()	Unknown
 	ApplicationInspector.Commands.dll!Microsoft.ApplicationInspector.Commands.AnalyzeCommand.AnalyzeCommand(Microsoft.ApplicationInspector.Commands.AnalyzeCommandOptions opt)	Unknown
>	TestAI1.dll!TestAI1.Program.Main(string[] args) Line 11	C#

```

I believe this might be due to the LogFileLevel not being assigned in [AnalyzeCommand.cs](https://github.com/microsoft/ApplicationInspector/blob/7446318a1d09939afd2b4dbe4c0647fdd94a53b3/AppInspector/Commands/AnalyzeCommand.cs#L74)

**Additional context**
Using the NuGet version 1.1.21 on .NET Core 3.1

**Comment by guyacosta** [comment]
investigating

**Comment by guyacosta** [comment]
The first issue is the call order above does not set the source path in the options object before passing it to the analyzecommand constructor :).  It will throw an exception on the directory or file being invalid which is correct but I can clarify the log error since there will be no file name to report to help.  In addition I did find the log level was not set by default which could cause an issue.  The logging setup path changed recently.  High priority on next fix after this is missing unit tests to avoid missing a test path.

**Comment by scovetta** [comment]
Thanks! If you send me over a .nupkg I can test it locally to make sure we're good.

**Comment by guyacosta** [comment]
Will  do.  Just improving the error msg on null source file for clarify in log -2 minutes.
