### ISSUE TITLE
Add Android intents scanning

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#258]
We should add detection for Android [Intents](https://developer.android.com/guide/components/intents-common) to Application Inspector.

**Comment by gfs** [comment]
For iOS how this works might be interesting
https://github.com/delba/Permission

**Comment by gfs** [comment]
For BSD you could look at pledges: https://man.openbsd.org/pledge.2

**Comment by gfs** [comment]
UWP: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by guyacosta** [comment]
I'm thinking the IOS, BSD and UWP are all in a somewhat related but distinct category i.e. permissions request/grant rather than the general request for a custom operation to be invoked through a general process create call or Intents which indirectly achieves a similar result if a process exists to service the request.  I'll move the permissions related support request to another Issue.

**Comment by scovetta** [comment]
I think we should add the specific intents instead of just usage of intents -- meaning things like ACTION_SET_ALARM. Might need to separate those out into the relevant category instead of bucketing them into a general intent tag.

**Comment by guyacosta** [comment]
Note there a LOT of them. Will look them over this weekend to propose which specific intents to include and drop the list here for discussion.

**Comment by guyacosta** [comment]
New support added for "Device.Permissions..." for Android, iOS, UWP for Java, Kotlin languages.
