### ISSUE TITLE
Limit excerpt size.

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#548]
**Is your feature request related to a problem? Please describe.**
Sometimes, in some of our projects, our team are including in the code folders ofuscated javascript libraries, big files in only one line. When a rule match something in the file, the result json contains the whole file in the excerpt field of the result json file. When it matches several times, it produce an unmanageable large file.

Example:
```
{
        "ruleId": "XAI020600",
        "ruleName": "Development Framework: React",
        "ruleDescription": "Development Framework: React",
        "tags": [
          "Framework.Development.React"
        ],
        "severity": "Moderate",
        "pattern": "react",
        "confidence": "High",
        "type": "String",
        "language": "javascript",
        "fileName": "./code/gptxcore/web/web_portal/build/bundle.js",
        "sample": "react",
        "excerpt": "/*! For license information please see bundle.js.LICENSE.txt */\n(()=\u003E{var __webpack_modules__={9635:function(module,exports,__webpack_require__){var __WEBPACK_AMD_DEFINE_ARRAY__,__WEBPACK_AMD_DEFINE_RESULT__,factory;module=__webpack_require__.nmd(module),function(e){var t,n,r,o,i,a,s=this;if(void 0!==__webpack_require__.g\u0026\u0026(s=__webpack_require__.g),\u0022undefined\u0022!=typeof window\u0026\u0026(s=window),\u0022log\u0022in(t=\u0022object\u0022==typeof s.console?s.console:null==s.console?s.console={}:{})||(t.log=function(){}),\u0022warn\u0022in t||(t.warn=t.log),void 0!==s.Opal)return t.warn(\u0022Opal already loaded. Loading twice can cause troubles, please fix your setup.\u0022),s.Opal;var l=this.Opal={};l.global=s,s.Opal=l,l.config={missing_require_severity:\u0022error\u0022,unsupported_features_severity:\u0022warning\u0022,enable_stack_trace:!0};var c=Object.hasOwnProperty,u=Function.prototype.bind,d=Object.setPrototypeOf,f=Array.prototype.slice,A=Array.prototype.splice,p=4;function h(e,t,n){\u0022string\u0022==typeof e?e[t]=n:Object.defineProperty(e,t,{value:n,enumerable:!1,configurable:!0,writable:!0})}function m(e,t){if(e)return e.$$const[t]}function g(e,t){var n,r,o;if(null!=e)for(n=0,r=(o=l.ancestors(e)).length;n\u003Cr;n\u002B\u002B)if(o[n].$$const\u0026\u0026c.call(o[n].$$const,t))return o[n].$$const[t]}function b(e,t,n){if(!n)return(e||o).$const_missing(t)}function v(e)
............."
        "startLocationLine": 2,
        "startLocationColumn": 1290922,
        "endLocationLine": 2,
        "endLocationColumn": 1290931
      }
```

etc.

**Describe the solution you'd like**
Excerpts should have a maximum number of characters for example, 1000, and when the line exceeded the max, the excerpt should contains match position +- 500 characters.

**Comment by gfs** [comment]
Thanks for the suggestion. I can see that's definitely an issue when you have such a long line, and this is something we should be able to address relatively soon.

In the meantime as a workaround, you should be able to use `--context-lines -1` to skip gathering excerpts entirely. That should at least reduce the output size and increase analysis speed - the locations of matches will be still be gathered just not the excerpt/samples.

**Comment by gfs** [comment]
I have a PR open that I believe will help with this issue: #550.

AppInspector already did try to limit the size of excerpts to 100 * numContextLines characters - however it did not account for minified/single line files where there may be one very long line. I've changed the logic so that is considered, and retained the existing behavior of setting a cap for excerpt size based on 100 * numContextLines characters (not including the finding itself), when fetching the full content of the number of lines of context would be excessive.

Note that this is a context specification for both sides, so if you specify numContextLines = 2 that would mean up to 200 characters on either side of the finding, 1 would mean 100 characters, the default is 3 for 300 characters on each side.

I'm potentially open to adding an explicit restriction for number of characters on each side rather than implicitly determining it from the number of lines, but a little hesitant to add another argument, as AI already has so many configuration parameters, so please let me know if this solution will be workable for you.
