### ISSUE TITLE
Insufficient memory to continue the execution of large program.

### ISSUE THREAD

**Issue by jasoneue** [microsoft/ApplicationInspector#91]
Tried running this against a large project, and I get an Insufficient memory error.  Looking at task manager, the .NET Core host process gets up to about 3GB and then fails.  Computer still has plenty of memory available

[log.txt](https://github.com/microsoft/ApplicationInspector/files/4092239/log.txt)

**Comment by guyacosta** [comment]
I fixed an issue that may improve this in [Release 1.0.21](https://github.com/microsoft/ApplicationInspector/releases/tag/v1.0.21).  Give that a try or send me a log file using the -v DEBUG option to learn more precisely where the error is occurring including the specific file scanned.

**Comment by guyacosta** [comment]
If compressed, did un-compressing make a difference?  We use a third party component for unzipping packages and occasionally see an issue for unknown reasons.

**Comment by guyacosta** [comment]
No further interactions with this party nor reported cases.  Closing.

**Comment by guyacosta** [comment]
The code was adjusted thanks to a submission #104 to avoid trying to read excessively large files before we try to process them.  The check was occurring too late.  In addition, I now write the name of the file being processed for decompression into the log so that should help if you see it again.  Let me know if not fixed now and I'll reopen this for additional investigation.  Get the latest code or I'll be releasing an update of binaries asap.
